#!/usr/bin/env ansible-playbook
---

# Setup scrub schedule
# cat /etc/cron.d/zfsutils-linux
### PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
###
### # Scrub the second Sunday of every month.
### 24 0 8-14 * * root [ $(date +\%w) -eq 0 ] && [ -x /usr/lib/zfs-linux/scrub ] && /usr/lib/zfs-linux/scrub

# Same as above, but using systemd timer
# cat /etc/systemd/system/zpool-scrub@.service
### [Unit]
### Description=Zpool `%i` scrub
### Requires=zfs.target
### After=zfs.target
###
### [Service]
### ExecStart=/sbin/zpool scrub %i
### Type=oneshot
# Then run it with a timer.

#######################################################################

# Increase the spa_slop_shift setting to 15%:
printf "options zfs spa_slop_shift=15" > /etc/modprobe.d/zfs.conf


############
## NOTES
############
#  o https://openzfs.github.io/openzfs-docs/Performance%20and%20Tuning/Module%20Parameters.html#spa-slop-shift


...

